### ISSUE TITLE
Add design: VexRISC-V Linux LiteX SoC with LiteDRAM and LiteEth (50T)

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/fpga-tool-perf#152]

**Comment by HackerFoo** [comment]
I think this is the `baselitex` design.

**Comment by tcal-x** [comment]
@HackerFoo you've seen this, right?

https://github.com/SymbiFlow/symbiflow-arch-defs/tree/master/xc/xc7/tests/soc/litex/base

**Comment by HackerFoo** [comment]
@tcal-x Yes, thanks.

**Comment by acomodi** [comment]
I believe this can actually be closed. This should be the baselitex project in FPGA tool perf.

**Comment by mithro** [comment]
Can we rename `baselitex` to `litex-vexriscv-ddr` or something? `baselitex` doesn't really mean much?

**Comment by HackerFoo** [comment]
The designs need documentation: https://github.com/SymbiFlow/fpga-tool-perf/issues/162

**Comment by HackerFoo** [comment]
I have the design building on Hydra as part of: https://github.com/SymbiFlow/fpga-tool-perf/issues/166
