### ISSUE TITLE
Adding wiki to fpga-tool-perf

### ISSUE THREAD

**Issue by ryancj14** [SymbiFlow/fpga-tool-perf#189]
The wiki that I have created is located at: https://github.com/ryancj14/fpga-tool-perf/wiki 

However, I don't have access to the wiki here. Is there a way to pull request to the wiki. I believe only owners with direct editing access can edit the wiki directly. Others could easily clone the files from the example wiki, and upload them here if they have access. Let me know how to proceed with this.

**Comment by mithro** [comment]
I made it so that anyone can modify the wiki at https://github.com/SymbiFlow/fpga-tool-perf/wiki

**Comment by mithro** [comment]
Please add your contents to our wiki.

Thanks for your efforts!

**Comment by ryancj14** [comment]
Ok I will be able to do by Saturday. Thank you!

**Comment by ryancj14** [comment]
I've successfully added the wiki.
