### ISSUE TITLE
vpr_xml.sh: use tarball instead

### ISSUE THREAD

**Issue by JohnDMcMaster** [SymbiFlow/fpga-tool-perf#20]
Currently we cd into symiflow-arch-defs and execute special targets to make the architecture XML files. However, ideally symiflow-arch-defs would spit out a distribution directory and/or archive such that we don't strictly need the symiflow-arch-defs repo to run VPR. I don't believe symiflow-arch-defs has this today, but update fpga-tool-perf once this is possible

**Comment by acomodi** [comment]
I believe this is solved, closing. A tarball is currently used to have all necessary data to run SymbiFlow
