### ISSUE TITLE
Add design: Ibex (200T)

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/fpga-tool-perf#237]

**Comment by mithro** [comment]
This design appears to have been added but is not running on CI for some reason? (The CI is downloading the 200T package.)

**Comment by mithro** [comment]
@acomodi -- What is the status here?

**Comment by mithro** [comment]
From https://colab.sandbox.google.com/drive/1Ny5OZ06R1KVjDykrAQbR0vTsTyiTT1Q7?usp=sharing#scrollTo=5so_LYXKqvjT it looks like `a200t` / `nexys-video` has landed as it appears to be running on Murax and Ibex is running on `a35t`?

**Comment by HackerFoo** [comment]
This design has been added.
