### ISSUE TITLE
Enable the arty a7 100T board

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/fpga-tool-perf#246]
With the availability of the artix 100T device, we can enable tests on the arty a7 board as well.

This translates into:
- adding the arty_a7-100T board specification
- adding constraint files to the existing tests

**Comment by mithro** [comment]
@wtatarski -- What is the status here? Do we have a pending pull request? Which designs will the a100t be enabled on?

**Comment by wtatarski** [comment]
@mithro 
Yes. The PR is #254 
Actually @acomodi  works on it now.
