### ISSUE TITLE
Set up CI for repository

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/fpga-tool-perf#27]

**Comment by mithro** [comment]
Is this done?

**Comment by acomodi** [comment]
@mithro There is an initial Travis CI that verifies the formatting. For running tests we need Kokoro.

**Comment by mithro** [comment]
@acomodi - Copy the configs from the symbiflow-arch-defs / prjxray repos and I'll set up the Google side.

**Comment by acomodi** [comment]
This can be closed as CI is already set up
