### ISSUE TITLE
Add Vivado support

### ISSUE THREAD

**Issue by mithro** [SymbiFlow/fpga-tool-perf#28]

**Comment by kgugala** [comment]
Initial support has been added in #26

**Comment by mithro** [comment]
Does this support both Vivado and Yosys(synth)+Vivado(pnr)?

**Comment by mithro** [comment]
Does this support both Vivado and Yosys(synth)+Vivado(pnr)?

**Comment by kgugala** [comment]
no, this is only for pure Vivado run

**Comment by kgugala** [comment]
this is done with #38
