### ISSUE TITLE
Build is failing because Pip can't install prjxray

### ISSUE THREAD

**Issue by HackerFoo** [SymbiFlow/fpga-tool-perf#289]
```
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement prjxray (from fasm2bels)
ERROR: No matching distribution found for prjxray
```

**Comment by HackerFoo** [comment]
Latest failing build: https://github.com/SymbiFlow/fpga-tool-perf/commit/1712cb13628c1485b5c58e0be387eeb73358e86f

**Comment by acomodi** [comment]
There is a PR [here](https://github.com/SymbiFlow/fpga-tool-perf/pull/288) to fix this. Once that goes green we can merge it and the issue should be gone.
