### ISSUE TITLE
Add FPGA interchange nextpnr implementation

### ISSUE THREAD

**Issue by litghost** [SymbiFlow/fpga-tool-perf#316]
Initially only simple circuits will work, e.g. a counter.  As more complicated circuit support is completed, add remaining circuits.

**Comment by kowalewskijan** [comment]
I guess we can do this similarly as other toolchains:
* introduce a conda package for fpga-interchange nextpnr variant (target repo: https://github.com/hdl/conda-eda/tree/master/pnr/nextpnr)
* add nextpnr_fpga_interchange target to the fpga-tool-perf and enable supported designs

**Comment by tmichalak** [comment]
This has been done in #331
