### ISSUE TITLE
baselitex-nexus run is not showing up in table

### ISSUE THREAD

**Issue by tcal-x** [SymbiFlow/fpga-tool-perf#369]
Hi @acomodi , I probably missed something in my recent PR #366  -- I don't see any results in the table here:

https://symbiflow.github.io/fpga-tool-perf/?elem_id=NEXUS-LIFCL-40-9BG400CES-status

**Comment by acomodi** [comment]
@tcal-x There was a bug that prevented to getting the right project name, opened fix in https://github.com/SymbiFlow/fpga-tool-perf/pull/370

**Comment by acomodi** [comment]
@tcal-x Just found another bug, for which the `baselitex-nexus` test was incorrectly using the `baselitex` source files, generating a failure. Fixed here: https://github.com/SymbiFlow/fpga-tool-perf/pull/371

**Comment by acomodi** [comment]
Baselitex data can now be correctly seen. Closing
