### ISSUE TITLE
Make symbiflow toolchain installation dynamic

### ISSUE THREAD

**Issue by acomodi** [SymbiFlow/fpga-tool-perf#75]
Currently the symbiflow install package is hardcoded.

A more dynamic way of getting the package would be required

**Comment by mithro** [comment]
I don't quite understand what feature you are proposing here?

**Comment by acomodi** [comment]
Currently the symbiflow toolchain has a fixed version, instead of pointing to a `latest` version. This is more a symbiflow-arch-defs side enhancement I suppose

**Comment by acomodi** [comment]
This was fixed in https://github.com/SymbiFlow/fpga-tool-perf/pull/290. Closing
